### ISSUE TITLE
Voting is a one shot action

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#108]
At the moment the jury member, during the litigation phase, can change his mind a few times in the voting preference.
However, this elasticity should not be allowed. The vote has to be a one-shot preference, there is no room for changing it.
The reason is that this info is currently stored on DB but (in future) it has to be stored on-chain (in the blockchain) and the back and forward don't fit the tech (because unreasonably expensive).
![image](https://user-images.githubusercontent.com/598726/198900757-260d4aa9-5912-44f3-a6c0-dafe6dbdbc88.png)

**Comment by AltiMario** [comment]
Make sure the feature works properly via the backend as well (as always has to be done). 
Consider a malicious user which accesses the API directly (e.g. via CLI), obviously, he bypasses the alert. So, just make sure that when the value is already stored it cannot be changed anymore (returning also a proper error message if it happens).

**Comment by pushpak-edu** [comment]
in the PORCE project how can we register user? Or I need to run API directly. I couldn't find any migration or setup for local users @AltiMario

**Comment by pushoo-sharma** [comment]
in the PORCE project how can we register user? Or I need to run API directly. I couldn't find any migration or setup for local users @AltiMario

**Comment by AltiMario** [comment]
hello @pushoo-sharma sorry for the delay in my reply, I completely missed this comment :-( 
I'm super happy about your interest in the project. 
I suggest looking at our wiki to understand the platform in general, but in particular, to answer your question read here https://github.com/e-Learning-DAO/POCRE/wiki/Wallet-connection
It is intended to be a web3 application (work is still in progress) and the registration/login is via crypto (Cardano) wallet.
If you want more info, don't hesitate to contact me.
