### ISSUE TITLE
Entity-Relationship data structure design

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#11]
Having already clarified the workflow and wireframes, it is possible now to define all the entities and the system, creating an entity-relationship data structure for the overall project.
It is worth mentioning that at this stage we are not taking into account any blockchain peculiarity (nor layer1 and 2).

The ER diagram has to be designed as a typical cloud (centralised) application. In the second stage, we will decide what data (and components) have to be stored in the blocks and only in the final stage (when hydra is stable and released) we will build the layer 2 engine.

**Comment by kritical0613** [comment]
Hello @AltiMario 
I just made a simple diagram for the Scenario 01~02.
Since It would contain so many mistakes and I am looking forward to hear your opinion.
Thanks.

https://app.gleek.io/diagrams/OVVDTZcsxpT8BWAWoSKJSg

**Comment by AltiMario** [comment]
I can't find yet enough time to look properly into details, please @GruDev325 add also your eyes.
The info to understand the workflow/logic is in Miro.
After your evaluation, I will join you both for a final review. Let's work together this is an important task.

**Comment by kritical0613** [comment]
Hello @GruDev325 
Can you have a look at the diagram about the Scenario 01~02?

**Comment by AltiMario** [comment]
thank you @kritical0613 
![gleek-N3u4T9dueMJcJpLgWPBtOw](https://user-images.githubusercontent.com/598726/180742093-720748d3-1678-4fc5-bcae-9ce4e2ab3e2e.png)

**Comment by AltiMario** [comment]
fixed with these were the missing columns
- 'user_id' column missing on 'creation' table, 'creation' table has a one-to-one relation with 'users' table (I added ‘author_id’ column to 'creation' table)
- ‘creation_materials’ column missing on 'creation' table, 'creation' table has a one-to-many relation with ‘material’ table (I added ‘materials’ column to 'creation' table)
- ‘decisions’ column missing on ‘litigation’ table, ‘litigation’ table has a one-to-many relation with ‘decisions’ table (I added ‘decisions’ column to 'litigation' table)
![image](https://user-images.githubusercontent.com/598726/189116939-0cd0fa58-f04f-4e10-9c98-b03fb1629837.png)
thanks @huzaifa-99

**Comment by ricvale0128** [comment]
Looks better!
Thanks for your effort.
