### ISSUE TITLE
wrong status for recognised material

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#144]
When the user doesn't recognise his material (not declined/approved)
![image](https://user-images.githubusercontent.com/598726/202690890-d58e3183-3104-47b0-80fa-6dec2045b13e.png)

other users view the associated material in a wrong status 
![image](https://user-images.githubusercontent.com/598726/202691569-aa4ca4ec-9b64-4fe7-97ae-6a0e580f719a.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://deploy-preview-143--pocre.netlify.app/recognitions/4726e865-012a-4e11-a291-458aff395863 as huzaifa user
2. switch user
3. access the same link
4. See the error

I think the "pending" status as to be the default status, before any changes by the user

**Comment by UmairMukhtar** [comment]
Done
