### ISSUE TITLE
Implement media format validation in API

### ISSUE THREAD

**Issue by huzaifa-99** [e-Learning-DAO/POCRE#175]
**Is your feature request related to a problem? Please describe.**
Currently in frontend we are not validating the media link with the selected media format. This is causing issues with the media rendering.

Example: I add a material to a creation, in that material I select type as image but in the link i provide a video link.
![Screenshot 2022-12-03 at 5 10 19 PM](https://user-images.githubusercontent.com/68777211/205440300-108fbb0a-9c08-43b1-be6c-c98eb690f70a.png)

**Describe the solution you'd like**
Handle the media format validation on api. 

In any api calls where we are getting a link and media type for the contents behind the link we will handle the media format validation. In the validation we will check the link for file formats and set the media type property on the api level with the correct format. In the frontend we will remove the media type field.

**Describe alternatives you've considered**
N/A

**Comment by AltiMario** [comment]
Before implementing from scratch, I suggest looking for a library that we can leverage for this scope. I think it is a common topic already been solved by someone, in a generic manner with a lib.

**Comment by AltiMario** [comment]
What do you think about these basic libs? 
https://github.com/jshttp/mime-types
https://github.com/nwaughachukwuma/url-exists-nodejs

**Comment by AltiMario** [comment]
I think @Kosticdev0421 is experimenting with this lib https://www.npmjs.com/package/file-type

**Comment by AltiMario** [comment]
@Kosticdev0421 @huzaifa-99 
I tested the last merge and I believe something is missing
![image](https://user-images.githubusercontent.com/598726/209168204-db39724c-2a1f-456a-85f3-efcb8074748f.png)

I can see from the API side something is changed (I haven't tested it) but from the frontend it doesn't seem to me that this new feature is called. 
How it is supposed to work?

**Comment by AltiMario** [comment]
Removing the file type section (in the frontend) is an option, but I would prefer to modify how the interface works. Instead of asking for the user input, let's return the file type that the function gets.
If the api catches an "unknow" file type, send it back (from API to frontend) an alert to the user and do not allow the submission ("Add File").
