### ISSUE TITLE
Fixing ER model

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#21]
We found a few issues with the ER model, some are fixed already but others are not yet. 
Here some:  
1- Missing creation_date field in the 'creations table'
2- A tag can belong to 1 or many creations (1 to many relations from 'tags' to 'creation' table)

Please comment on this ticket to update on other bugs discovered.

**Comment by huzaifa-99** [comment]
3. A user can send 0 or many invitations (0 to many relation from 'users' to 'invitation' table)
4. A creation can have 0 or many materials (0 to many relation from 'creation' to 'material' table)
5. A user can create 0 or many materials (0 to many relation from 'user' to 'material' table)

Please see updated changes below and let me know if any issues. Thanks
![POCRE ERD](https://user-images.githubusercontent.com/68777211/191055718-54460557-9fad-4fc2-9575-0c98c580cf17.png)

**Comment by huzaifa-99** [comment]
> 3. A user can send 0 or many invitations (0 to many relation from 'users' to 'invitation' table)
> 4. A creation can have 0 or many materials (0 to many relation from 'creation' to 'material' table)
> 5. A user can create 0 or many materials (0 to many relation from 'user' to 'material' table)
> 
> Please see updated changes below and let me know if any issues. Thanks ![POCRE ERD](https://user-images.githubusercontent.com/68777211/191055718-54460557-9fad-4fc2-9575-0c98c580cf17.png)

6. A user can receive 0 or many invitations (0 to many relation from 'invitation' to 'users' table)
![POCRE ERD](https://user-images.githubusercontent.com/68777211/191060248-2de0c8d6-f5ad-47d4-ab5d-2e391307f010.png)

**Comment by huzaifa-99** [comment]
> > 3. A user can send 0 or many invitations (0 to many relation from 'users' to 'invitation' table)
> > 4. A creation can have 0 or many materials (0 to many relation from 'creation' to 'material' table)
> > 5. A user can create 0 or many materials (0 to many relation from 'user' to 'material' table)
> > 
> > Please see updated changes below and let me know if any issues. Thanks ![POCRE ERD](https://user-images.githubusercontent.com/68777211/191055718-54460557-9fad-4fc2-9575-0c98c580cf17.png)
> 
> 6. A user can receive 0 or many invitations (0 to many relation from 'invitation' to 'users' table)
>    ![POCRE ERD](https://user-images.githubusercontent.com/68777211/191060248-2de0c8d6-f5ad-47d4-ab5d-2e391307f010.png)

7. A user can create 0 or many creations (0 to many relation from 'user' to 'creation' table)
![POCRE ERD](https://user-images.githubusercontent.com/68777211/191069814-93188f85-a710-4735-a461-97b8bf9ed7de.png)

**Comment by huzaifa-99** [comment]
8. A user can create 0 or many litigations (0 to many relation from 'user' to 'litigation' table)
9. A litigation can have 0 or 1 material (0 or 1 relation from 'litigation' to 'material' table)
10. One litigation will always have one creation (1 to 1 relation between 'creation' and 'litigation' table)
![POCRE ERD](https://user-images.githubusercontent.com/68777211/193343000-1a3da7eb-cd02-447c-bde2-21b9cad7c4b0.png)
