### ISSUE TITLE
Add the avatars of the authors

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#24]
We want to show random avatars of the authors of the materials (used in the "creation" displayed on this page).
It is mainly to give evidence that there is co-creation. All of these users are contributors to the new opera.
Avatars are not clickable. In the future, we could display a new section with materials related to authors. 
![image](https://user-images.githubusercontent.com/598726/190922817-b82b0004-e3b6-468b-9362-de08f79d8e48.png)

**Comment by AltiMario** [comment]
when I change the use I suppose the avatar should change
![image](https://user-images.githubusercontent.com/598726/191465875-1cef5241-fd51-4e73-9d74-e8dc2404643b.png)

please stop until "Heath Fahey", are enough and after they just repeat
![image](https://user-images.githubusercontent.com/598726/191465435-349ecb0f-8198-4ad2-be72-f3156d3f2f8b.png)

**Comment by AltiMario** [comment]
At this stage, they are dummy users. As you mentioned they come from https://pravatar.cc I think this component has to be dynamic as well.
![image](https://user-images.githubusercontent.com/598726/191478565-0e5b4ff8-7455-4738-8961-f06c572319d0.png)

**Comment by huzaifa-99** [comment]
Updated here: [8cbda33](https://github.com/e-Learning-DAO/POCRE/pull/19/commits/8cbda335153a8eb0bae7aa8956c6960d4019a553)
