### ISSUE TITLE
Missing "add file" features on materials

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#26]
This bug is probably related to the documented issue with the ER model.
What is missing here is the option to add multiple files (representing multiple materials) to a single author, in relation to a single creation (alias opera).
It was present in the workflow but sadly missed in the design implementation.
![image](https://user-images.githubusercontent.com/598726/190925958-a22079fc-15ee-4dc4-b393-4e6a3204905a.png)

**Comment by huzaifa-99** [comment]
Does it relate to Point # 5 https://github.com/e-Learning-DAO/POCRE/issues/30#issue-1378779814?

**Comment by AltiMario** [comment]
yes, sorry if I confused you. There it is about missing frontend component, here it is more functionality (backend, DB, API, etc)

**Comment by huzaifa-99** [comment]
I think we should also add a 'Skip' button somewhere. A creation may not be using any material of another author. Please let me know if it makes sense.

**Comment by AltiMario** [comment]
well spotted ;-)
