### ISSUE TITLE
Features and UI refactoring for proof of authorship

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#36]
Some components of the wireframe were missing but in general, this is a re-thinking of the functionalities desired
![image](https://user-images.githubusercontent.com/598726/191552929-f33a60b6-3ec2-4c8c-aff7-5bad6b9d65f3.png)

**Comment by AltiMario** [comment]
![image](https://user-images.githubusercontent.com/598726/191555374-b1b29a38-7947-4ece-8caf-c915c8ad900d.png)

**Comment by AltiMario** [comment]
![image](https://user-images.githubusercontent.com/598726/191556560-3d700cc0-b397-421c-bf02-5d987718ac71.png)

**Comment by AltiMario** [comment]
I just realized this is needed
![image](https://user-images.githubusercontent.com/598726/192089574-6755fcf1-8e7a-4c9f-b51b-eb0b992260b1.png)

**Comment by AltiMario** [comment]
A little issue
![image](https://user-images.githubusercontent.com/598726/192374263-3d99cd64-0cec-4b52-83a5-7fb4a1c1bdf1.png)

**Comment by huzaifa-99** [comment]
> A little issue ![image](https://user-images.githubusercontent.com/598726/192374263-3d99cd64-0cec-4b52-83a5-7fb4a1c1bdf1.png)

Fixed [here](https://github.com/e-Learning-DAO/POCRE/pull/19/commits/30448f1544d7a5c56a131fcb0e2233077051bcb1)
