### ISSUE TITLE
Associate the logged user to each functionality

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#46]
The user logged in (currently using pre-built users) has to be able to see his data on every page.
At the moment this is only possible on the "creation" feature. You can see an example of how to do that for other pages here
https://github.com/e-Learning-DAO/POCRE/blob/web-frontend/src/components/Layout/Header/useHeader.js#L6
Users not logged in cannot access any page other than "credits".
At this stage, this check is only required for the front-end side. A proper authentication backend at the API level is planned for later.

![image](https://user-images.githubusercontent.com/598726/192319411-47bd6e29-2004-4b63-afba-0201562ef151.png)

**Comment by Mahdi-Soultana** [comment]
i think this ticket is done
