### ISSUE TITLE
Materials recognition refactoring

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#47]
There is some flaw in the design compared with the wireframe.
This is the refactoring of the "inbox" section, some labelling is already changed and a couple of new requirements have been added.
![image](https://user-images.githubusercontent.com/598726/192491504-caad0e69-7b26-4fb8-b335-8c8da02f7c8b.png)

**Comment by AltiMario** [comment]
![image](https://user-images.githubusercontent.com/598726/192501194-8de0ee9c-0a53-40a0-98ef-16e8bfe4e121.png)

**Comment by AltiMario** [comment]
just to clarify, the "preview" button is already implemented here, needs to be only called
![image](https://user-images.githubusercontent.com/598726/193059737-fbaff2d9-a4f7-4e1b-8ead-179d67e67e9c.png)
![image](https://user-images.githubusercontent.com/598726/193059791-b244125e-42ba-4691-a63e-d622a94c1356.png)

**Comment by AltiMario** [comment]
let me clarify after the last changes.
The main missing things in the current implementation are:
- open material function
- open preview function ( the one clarified here https://github.com/e-Learning-DAO/POCRE/issues/47#issuecomment-1262370434)

In this screenshot, there is an explanation of where to put them with a bit of reorganisation of the view  
![image](https://user-images.githubusercontent.com/598726/195300342-bda38dbc-5ecc-40d9-bba1-ccb2c26c9c67.png)

**Comment by AltiMario** [comment]
@huzaifa-99 the current activity of this ticket is "47-materials-recognition-refactoring" however I believe it is not in sync with the last "web-frontend" and I think it is not fully implemented (or at least not as I described in this ticket and definitely not in line with your last modification of the creation part).
Please have a look and take leadership of this task. If you can, when finished, you could go through the changes to help @adisagar2003 understand the modification.

**Comment by huzaifa-99** [comment]
Some other things to add.

### Related to architecture
1. Typescript
2. React Query (HTTP layer and data cache management, this can also replace global state solution if done properly)
3. Global Storage

### Related to DX (dev experience) 
4. Using path alias (with intellisense)
5. Adding IDE config (including extensions setup) for vs code (I assume most people use this)
6. Adding editor config for other IDEs
7. Adding config files for checking style consistency (https://stylelint.io/user-guide/configure/)
8. Adding https://github.com/get-alex/alex, this checks and warns about insensitive, inconsiderate writing
