### ISSUE TITLE
basic UI template

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#5]
Take the wireframe "UI - Layout - Collection - Overview.jpg" as a guideline and define a template of the overall platform.
Try to make it nice-looking and usable for the final user.
Provide a couple of proposals and store them in a defined directory.

**Comment by mithunrayy** [comment]
![UI - Layout - Collection - New Step 01](https://user-images.githubusercontent.com/70772035/179202704-2a111fab-1c02-413e-910f-6e0c86075613.png)
![UI - Layout - Collection - New Step 02](https://user-images.githubusercontent.com/70772035/179202717-8030898f-1a43-4105-8a1e-d802742bfd2c.png)
![UI - Layout - Collection - New Step 03](https://user-images.githubusercontent.com/70772035/179202729-1229dc33-5ac8-4117-bfec-b1bda6676a8e.png)
![UI - Layout - Collection - Overview](https://user-images.githubusercontent.com/70772035/179202731-07478c8d-53f6-4b5d-820c-9e6f1128e91f.png)
![UI - Layout - Collection - Overview-1](https://user-images.githubusercontent.com/70772035/179202738-f9a022fd-4fc4-4fe6-812b-9fe71ad361e9.png)
![UI - Layout - Invitation - Unknown format](https://user-images.githubusercontent.com/70772035/179202744-f8dc7587-7923-4055-bdb1-93d1f4404865.png)
![UI - Layout - Invitation - Video Preview](https://user-images.githubusercontent.com/70772035/179202749-5143acb5-3307-4306-b07d-46a73ca09869.png)
![UI - Layout - Invitation](https://user-images.githubusercontent.com/70772035/179202751-bf3ead2e-a3db-41d6-836b-c4aeafa5cd91.png)
