### ISSUE TITLE
UI template scenario #1

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#6]
create the templates for all wireframes involved in scenario #1

**Comment by AltiMario** [comment]
just to clarify @mithunrayy the scenario number is in the description of the wireframes images

**Comment by mithunrayy** [comment]
![UI - Layout - Collection - New Step 01](https://user-images.githubusercontent.com/70772035/179205697-db92a0f7-e557-4eea-bed5-e98d0e40a54f.png)
![UI - Layout - Collection - New Step 02](https://user-images.githubusercontent.com/70772035/179205705-add62080-4902-4dbc-a78c-ffca7944ab3b.png)
![UI - Layout - Collection - New Step 03](https://user-images.githubusercontent.com/70772035/179205710-b17e8cb9-1c69-4db7-9b36-6f348ec5bc45.png)
![UI - Layout - Collection - Overview](https://user-images.githubusercontent.com/70772035/179205715-1dc0a95f-dfda-4d4b-8956-662a8d51ba55.png)
![UI - Layout - Collection - Overview-1](https://user-images.githubusercontent.com/70772035/179205724-c15cfbff-d5cb-4377-9e66-85150903d52d.png)
![UI - Layout - Invitation - Unknown format](https://user-images.githubusercontent.com/70772035/179205729-b425fc71-4f3c-4760-8d65-795e6dc7c991.png)
![UI - Layout - Invitation - Video Preview](https://user-images.githubusercontent.com/70772035/179205734-64f02e32-37d8-4822-8132-10ab6699b905.png)
![UI - Layout - Invitation](https://user-images.githubusercontent.com/70772035/179205742-5fe74284-3b07-4c63-817f-6eb4064b38cd.png)

**Comment by AltiMario** [comment]
they are beautiful :-O

**Comment by mithunrayy** [comment]
Thank you! @AltiMario

**Comment by mithunrayy** [comment]
The Figma design is alright? @AltiMario
