### ISSUE TITLE
Refactoring routes, labels and functions

### ISSUE THREAD

**Issue by AltiMario** [e-Learning-DAO/POCRE#69]
Even if it doesn't seem important naming is extremely valuable to clarify the purpose of the things and so what to do and how.
Because of this topic, we need a bit of refactoring of naming for labels, routes and source functions
![image](https://user-images.githubusercontent.com/598726/196457957-c7c8f6cd-db03-469d-b78c-dc9a5bc274ea.png)

There are hundreds of wrong entries called "invitation" to rename into "recognition" 
![image](https://user-images.githubusercontent.com/598726/196456296-0f295265-b419-4507-ac69-0b719acfb142.png)

This is even worse, instead of credits there is credit card (obviously to rename)
![image](https://user-images.githubusercontent.com/598726/196459600-96697819-70b9-4332-a52d-df4f095f45b5.png)

I assume the DB tables/fileds are affected as well.
 
If you found something else don't hesitate to fix it.

**Comment by huzaifa-99** [comment]
Also some other things to add
Some other things to add.

### Related to architecture
1. Typescript
2. React Query (HTTP layer and data cache management, this can also replace global state solution if done properly)
3. Global Storage

### Related to DX (dev experience) 
4. Using path alias (with intellisense)
5. Adding IDE config (including extensions setup) for vs code (I assume most people use this)
6. Adding editor config for other IDEs
7. Adding config files for checking style consistency (https://stylelint.io/user-guide/configure/)
8. Adding https://github.com/get-alex/alex, this checks and warns about insensitive, inconsiderate writing

**Comment by AltiMario** [comment]
align the controllers naming with the right workflow, for example, "controllers/invitation.controller.ts" should be now "controllers/recognition.controller.ts".
At the moment in the source code "invitation" is everywhere :-(
